name: ChunkLocked
version: ${version}
main: fr.abdelnaim.chunklocked.ChunkLockedPlugin
api-version: '1.21'
author: abdelnaim
description: Progressive chunk locked survival mode.

commands:
  chunklocked:
    description: Manage the ChunkLocked game mode.
    usage: /chunklocked <info|reload|reset>
    aliases: [cl]
    permission: chunklocked.admin

permissions:
  chunklocked.admin:
    description: Allows using ChunkLocked admin commands.
    default: op
